#!/usr/bin/env bash
# Script: 0-transfer_file
# Description: Transfers a file from our client to a server using SCP.

# Check if all required parameters are provided
if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign parameters to variables
file_path="$1"
server_ip="$2"
username="$3"
ssh_key="$4"

# Transfer the file using SCP with StrictHostKeyChecking disabled
scp -o "StrictHostKeyChecking=no" -i "$ssh_key" "$file_path" "$username@$server_ip:~/"
