#!/usr/bin/env bash
# Script: 1-install_nginx_web_server
# Description: Configures a new Ubuntu machine to install and configure Nginx web server.
# Requirements:
#   - Installs Nginx on the server
#   - Configures Nginx to listen on port 80
#   - Allows incoming traffic on port 80 through the firewall
#   - Sets the owner of the /var/www directory to the current user
#   - Returns a page with the string "Hello World!" when queried at root / using curl

# Install nginx
sudo apt-get update
sudo apt-get install -y nginx

# Configure nginx to listen on port 80
sudo sed -i 's/#listen 80;/listen 80;/g' /etc/nginx/sites-available/default

# Configure firewall to allow incoming traffic on port 80
sudo ufw allow 'Nginx HTTP'

# Create the "Hello World!" page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Testing nginx configurations
sudo nginx -t

# Reloading nginx
sudo service nginx reload

# Prnt success message
echo '200'
